# Generated by Django 5.1.7 on 2025-03-09 06:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('content_link', models.URLField()),
                ('audio_file', models.FileField(upload_to='audios/')),
                ('category', models.CharField(choices=[('Hausa', 'Hausa'), ('Igbo', 'Igbo'), ('Yoruba', 'Yoruba'), ('Efik', 'Efik'), ('Tiv', 'Tiv')], max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
