# Generated by Django 5.1.7 on 2025-03-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiocontent',
            name='audio_file',
            field=models.FileField(upload_to=''),
        ),
    ]
