# Generated by Django 5.1.7 on 2025-03-13 16:42

import audio_scraper.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio_scraper', '0002_alter_audiocontent_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiocontent',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=audio_scraper.models.audio_upload_path),
        ),
    ]
